name: Cloudcore IAC

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

env:
  # credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for the terraform state.
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF }}
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: "ğŸš€ Apply terraform code changes"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: ğŸ› ï¸ Checkout source code
        uses: actions/checkout@v4

      - name: ğŸ“¦ Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3

      - name: ğŸ”§ Terraform Init
        id: init
        run: terraform init -backend-config "bucket=$BUCKET_TF_STATE"

      - name: ğŸ“ Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: âœ… Terraform Validate
        id: validate
        run: terraform validate

      - name: ğŸ“ Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out planfile

      - name: âŒ Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: ğŸš€ Terraform Apply
        id: apply
        if: steps.plan.outcome == 'success' && github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false -parallelism=1 planfile